prography/10th-5Team-BE

src/main/java/com/example/cherrydan/fcm/config/FirebaseConfig.java

refactor: prod 버전은 절대 경로로 실행

---

src/main/java/com/example/cherrydan/fcm/dto/NotificationRequest.java

@builder.default 함으로써 디폴트 값을 빌더 패턴을 사용할 시에 적용되게 수정하였습니다.

refactor: @builder.default add

---

src/main/java/com/example/cherrydan/common/entity/BaseTimeEntity.java

기존의 콜럼 이름이 created 였는데 createdAt으로 수정했습니다.

refactor: baseTimeEntity column refactor

---

src/main/java/com/example/cherrydan/mypage/controller/MyPageController.java
src/main/java/com/example/cherrydan/oauth/controller/GoogleAuthController.java
src/main/java/com/example/cherrydan/oauth/security/oauth2/CustomOAuth2UserService.java
src/main/resources/application-prod.yml

refactor: google oauth logic add

---

src/main/java/com/example/cherrydan/oauth/controller/GoogleAuthController.java

- 엔드포인트 api/auth/google/mobile -> api/auth/google/login으로 변경

refactor: api 양식 통일

---

src/main/java/com/example/cherrydan/oauth/controller/GoogleAuthController.java

refactor: swagger docs refactor

---

src/main/java/com/example/cherrydan/oauth/config/SecurityConfig.java

기존의 security config에 엔드포인트 추가했습니다.

refactor: google, kakao, naver endpoint add

---

src/main/resources/application-prod.yml

fix: db_url -> db_host

---

src/main/resources/application-prod.yml

fix: url modified

---

src/main/java/com/example/cherrydan/activity/service/ActivityServiceImpl.java
src/main/java/com/example/cherrydan/campaign/service/BookmarkServiceImpl.java
src/main/java/com/example/cherrydan/campaign/service/CampaignStatusServiceImpl.java
src/main/java/com/example/cherrydan/inquiry/repository/InquiryRepository.java
src/main/java/com/example/cherrydan/inquiry/service/InquiryService.java
src/main/java/com/example/cherrydan/oauth/repository/RefreshTokenRepository.java
src/main/java/com/example/cherrydan/oauth/security/jwt/CustomUserDetailsService.java
src/main/java/com/example/cherrydan/sns/repository/SnsConnectionRepository.java
src/main/java/com/example/cherrydan/user/controller/UserKeywordController.java
src/main/java/com/example/cherrydan/user/dto/KeywordCampaignAlertResponseDTO.java
src/main/java/com/example/cherrydan/user/repository/UserKeywordRepository.java
src/main/java/com/example/cherrydan/user/service/UserKeywordService.java

키워드 response를 dto로 반환하게 변경하였습니다.

feat: Add user soft delete and improve keyword alert DTO

---

src/main/java/com/example/cherrydan/activity/dto/ActivityNotificationResponseDTO.java
src/main/java/com/example/cherrydan/campaign/domain/CampaignStatus.java
src/main/java/com/example/cherrydan/user/controller/UserKeywordController.java

활동 삭제할 때의 request를 리스트로 받기로 수정

feat: Improve notification tracking and API consistency

---

src/main/java/com/example/cherrydan/fcm/service/FCMTokenService.java

userFcmToken builder에 isActive가 없어서 오류 났습니다.

userFcmToken builder add isActive

---

src/main/java/com/example/cherrydan/fcm/domain/UserFCMToken.java
src/main/java/com/example/cherrydan/user/domain/User.java

Remove UUID related logic from UserFCMToken and User entities

---

src/main/java/com/example/cherrydan/activity/controller/ActivityController.java
src/main/java/com/example/cherrydan/campaign/controller/BookmarkController.java
src/main/java/com/example/cherrydan/campaign/repository/CampaignStatusRepository.java
src/main/java/com/example/cherrydan/campaign/service/CampaignCategoryServiceImpl.java
src/main/java/com/example/cherrydan/mypage/controller/MyPageController.java
src/main/java/com/example/cherrydan/notice/controller/NoticeController.java
src/main/java/com/example/cherrydan/user/controller/UserController.java
src/main/java/com/example/cherrydan/user/controller/UserKeywordController.java

- 모든 컨트롤러에서 페이지네이션 설명을 Request Body에서 Query Parameter로 수정
- 긴 패키지명 축약 (org.springframework.data.domain.Sort.Direction.DESC → Sort.Direction.DESC)
- 쿼리 파라미터 예시 및 복수 정렬 조건 설명 추가
- Campaign 테이블 조회 시 is_active=1 조건을 첫 번째로 배치하여 쿼리 최적화
- BookmarkRepository에 findByUserIdAndIsActiveTrue 메서드 추가
스웨거 수정했습니다.

docs: 페이지네이션 API 문서 수정 및 쿼리 최적화

---

src/main/java/com/example/cherrydan/notice/domain/Notice.java
src/main/java/com/example/cherrydan/notice/dto/NoticeResponseDTO.java

notice_category -> 삭제
image_url -> 아래와 같이 변경
```
@ElementCollection 
@CollectionTable(name = "notice_images", joinColumns = @JoinColumn(name = "notice_id"))
```

refactor: 소식에서 이미지 여러개 보일 수 있게 엔티티 수정

---

src/main/resources/application-prod.yml

refactor: prod-yml 수정

---

src/main/java/com/example/cherrydan/oauth/security/jwt/JwtAuthenticationFilter.java

기존의 DB조회를 하던 필터 구조를 stateless로 바꿨습니다.

refactor: 완벽한 stateless 구조로 변경

---

src/main/java/com/example/cherrydan/user/dto/UserDto.java

refactor: userDto 수정 -> null 체크 추가

---

src/main/java/com/example/cherrydan/campaign/controller/CampaignCategoryController.java
src/main/java/com/example/cherrydan/campaign/service/CampaignCategoryService.java
src/main/java/com/example/cherrydan/campaign/service/CampaignCategoryServiceImpl.java

- 카테고리 검색 API에 누락된 title 파라미터 추가했습니다!

Fix: Category 검색 API 내 누락된 title 파라미터 추가

---

src/main/java/com/example/cherrydan/oauth/security/jwt/JwtAuthenticationFilter.java

``` java
catch (ExpiredJwtException e) {
log.warn("토큰이 만료되었습니다: {}", e.getMessage());
sendErrorResponse(response, HttpStatus.UNAUTHORIZED, "토큰이 만료되었습니다.");
```
ExpiredJwtException 캐치 로직을 필터에 추가하였습니다.

refactor: add ExpiredJwtException catch logic

---

src/main/java/com/example/cherrydan/fcm/dto/NotificationResultDto.java
src/main/java/com/example/cherrydan/fcm/service/NotificationService.java
src/main/java/com/example/cherrydan/user/service/UserKeywordService.java
src/test/java/com/example/cherrydan/fcm/service/NotificationServiceTest.java

- 멀티 캐스트 메서드 변경했습니다.
- 푸시 알람 콜백 로직을 변경했습니다.

refactor: firebase 멀티 캐스트 매서드 변경

---

src/main/resources/application.yml

Chore: 기본 실행 환경 dev로 임시 변경

---

.github/workflows/ci-cd.yml

refactor: dev & prod 환경분리

---

src/main/java/com/example/cherrydan/campaign/domain/RegionGroup.java

Fix: 지역 기타 대응 안되는 문제 개선

---

src/main/java/com/example/cherrydan/oauth/security/jwt/JwtTokenProvider.java
src/main/resources/application-dev.yml

Revert "Refactor: 엑세스 토큰 임시로 1분으로 변경"

---

src/main/java/com/example/cherrydan/oauth/security/jwt/JwtTokenProvider.java
src/main/resources/application-dev.yml

Fix: 지역 기타(etc) 오류 수정

---

.github/workflows/ci-cd.yml
Dockerfile
build.gradle
src/main/java/com/example/cherrydan/oauth/config/RestTemplateConfig.java
src/main/java/com/example/cherrydan/oauth/config/SecurityConfig.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/main/resources/logback-spring.xml

#109 
dev 환경에 ECR + OIDC 기반 Blue-Green 배포와 Prometheus, Grafana, Loki를 활용한 통합 모니터링 시스템을 구축했습니다.
기존 JAR 기반 배포 방식에서 컨테이너 기반 배포로 전환하여 무중단 배포를 구현하고, 애플리케이션과 인프라에 대한 통합 모니터링 환경을 제공하기 위해 이 변경이 필요했습니다.
- Graceful Shutdown: 30초 대기 시간으로 무중단 배포 지원
- Actuator 엔드포인트: Prometheus 메트릭과 헬스체크 API 활성화
- JSON 로그 포맷: Loki 수집을 위한 구조화된 로깅 (Logback 설정)
- 의존성 추가: Micrometer Prometheus, Logstash Logback Encoder
- Dockerfile: Distroless Java 17 기반 경량 이미지
- Blue-Green 배포: 8080/8081 포트를 통한 무중단 배포
- ECR 통합: AWS ECR을 활용한 컨테이너 이미지 저장소
- OIDC 인증: 비밀키 없는 GitHub Actions 배포
- GitHub Actions: ECR 이미지 빌드 및 푸시 자동화
- 배포 스크립트: Graceful 배포 프로세스 (헬스체크 → 트래픽 전환 → 기존 서비스 대기 → 종료)
- 환경 분리: develop 브랜치 → dev 환경 자동 배포
- Prometheus: Spring Boot 메트릭 수집
- Grafana: 대시보드 및 시각화
- Loki: 로그 집중화
- Promtail: 컨테이너 로그 수집
```gradle
// 모니터링 의존성 추가 …
```

feat: monitoring yml & logback.xml

---

src/main/java/com/example/cherrydan/campaign/dto/BookmarkResponseDTO.java
src/main/java/com/example/cherrydan/campaign/dto/CampaignResponseDTO.java

Chore: 캠페인 신청 마감 일에 따른 노출 문구 변경

---

src/main/java/com/example/cherrydan/campaign/repository/BookmarkRepository.java
src/main/java/com/example/cherrydan/campaign/service/BookmarkServiceImpl.java

- 기준 일자를 변경했습니다. `발표일 -> 신청 마감일`

Fix: 북마크 기준 일자를 발표일 -> 신청 마감일로 변경

---

src/main/java/com/example/cherrydan/oauth/config/SecurityConfig.java

Fix: 앱 버전 API JWT 인증 비활성화

---

src/main/java/com/example/cherrydan/campaign/dto/BookmarkResponseDTO.java

- 북마크 내 신청 마감 일자 기준 필드가 발표일자로 되어있어 변경했습니다.

Fix: 북마크 신청 마감 일자 기준 필드 변경

---

.github/workflows/drafter.yaml

Chore: Release Note 자동 생성 Workflow 수정

---

src/main/java/com/example/cherrydan/campaign/dto/BookmarkResponseDTO.java
src/main/java/com/example/cherrydan/notice/domain/NoticeBanner.java
src/main/java/com/example/cherrydan/notice/dto/NoticeBannerResponseDTO.java
src/main/java/com/example/cherrydan/notice/repository/NoticeBannerRepository.java
src/main/java/com/example/cherrydan/notice/service/NoticeBannerServiceImpl.java

- 홈 화면 배너 DTO 개선
- 북마크 DTO - 내 체험단 상태와 동일하게 전체 수정
- 홈 화면 이미지 제거, 백그라운드 컬러 추가
- 북마크, 내 체험단 동일 규격으로 가져가고 싶은 니즈가 있어 수정

Refactor: campaign dto update
